-- Run after 005. Existing submissions and legacy student-number data are preserved.
begin;
create or replace function public.roster_name(p_name text) returns text
language sql immutable as $$ select lower(trim(regexp_replace(coalesce(p_name, ''), '[[:space:]]+', ' ', 'g'))) $$;

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 120),
  created_at timestamptz not null default now()
);
create unique index if not exists classes_owner_name on public.classes(user_id, public.roster_name(name));
create table if not exists public.class_students (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  first_name text not null check (length(trim(first_name)) between 1 and 100),
  last_name text not null check (length(trim(last_name)) between 1 and 100),
  created_at timestamptz not null default now()
);
create unique index if not exists class_student_name on public.class_students(class_id, public.roster_name(first_name), public.roster_name(last_name));
create table if not exists public.quiz_classes (
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  class_id bigint not null references public.classes(id) on delete cascade,
  primary key (quiz_id, class_id)
);
alter table public.classes enable row level security;
alter table public.class_students enable row level security;
alter table public.quiz_classes enable row level security;
drop policy if exists classes_owner on public.classes;
create policy classes_owner on public.classes for all to authenticated
  using (user_id = auth.uid() and public.is_workspace_user())
  with check (user_id = auth.uid() and public.is_workspace_user());
drop policy if exists students_owner on public.class_students;
create policy students_owner on public.class_students for all to authenticated
  using (exists(select 1 from public.classes c where c.id = class_id and c.user_id = auth.uid()) and public.is_workspace_user())
  with check (exists(select 1 from public.classes c where c.id = class_id and c.user_id = auth.uid()) and public.is_workspace_user());
drop policy if exists quiz_classes_owner on public.quiz_classes;
create policy quiz_classes_owner on public.quiz_classes for all to authenticated
  using (exists(select 1 from public.quizzes q where q.id = quiz_id and q.user_id = auth.uid()) and public.is_workspace_user())
  with check (exists(select 1 from public.quizzes q join public.classes c on c.user_id = q.user_id where q.id = quiz_id and c.id = class_id and q.user_id = auth.uid()) and public.is_workspace_user());
grant select, insert, update, delete on public.classes, public.class_students, public.quiz_classes to authenticated;
grant usage, select on sequence public.classes_id_seq, public.class_students_id_seq to authenticated;

alter table public.quizzes add column if not exists time_limit_minutes integer
  check (time_limit_minutes between 1 and 480);
alter table public.attempts add column if not exists roster_student_id bigint references public.class_students(id) on delete set null;
alter table public.attempts add column if not exists class_id bigint references public.classes(id) on delete set null;
alter table public.attempts add column if not exists class_name text;
alter table public.attempts add column if not exists first_name text;
alter table public.attempts add column if not exists last_name text;
alter table public.attempts add column if not exists expires_at timestamptz;
create index if not exists attempts_pending_deadline on public.attempts(expires_at) where completed_at is null;

-- No roster names are exposed on public exam pages, only assigned sections.
create or replace function public.exam_classes(p_share_token uuid)
returns table(id bigint, name text) language sql stable security definer set search_path = public as $$
  select c.id, c.name from public.classes c join public.quiz_classes qc on qc.class_id = c.id
  join public.quizzes q on q.id = qc.quiz_id where q.share_token = p_share_token and q.is_published and c.user_id = q.user_id order by c.name;
$$;
revoke all on function public.exam_classes(uuid) from public;
grant execute on function public.exam_classes(uuid) to anon, authenticated;

-- Save settings and class assignments atomically.
create or replace function public.save_quiz_settings(p_quiz_id bigint, p_title text, p_description text, p_published boolean, p_lockdown boolean, p_minutes integer, p_classes bigint[])
returns public.quizzes language plpgsql security definer set search_path = public as $$
declare v_quiz public.quizzes;
begin
  if not public.is_workspace_user() then raise exception 'Workspace account required'; end if;
  select * into v_quiz from public.quizzes where id = p_quiz_id and user_id = auth.uid() for update;
  if not found then raise exception 'Quiz not found'; end if;
  if coalesce(trim(p_title), '') = '' then raise exception 'Enter a quiz title'; end if;
  if exists(select 1 from unnest(p_classes) cid where not exists(select 1 from public.classes c where c.id = cid and c.user_id = auth.uid())) then raise exception 'Choose your own classes'; end if;
  if p_published and coalesce(cardinality(p_classes), 0) = 0 then raise exception 'Assign at least one class before publishing'; end if;
  update public.quizzes set title = trim(p_title), description = nullif(trim(p_description), ''), is_published = p_published, lockdown_enabled = p_lockdown, time_limit_minutes = p_minutes where id = p_quiz_id returning * into v_quiz;
  delete from public.quiz_classes where quiz_id = p_quiz_id;
  insert into public.quiz_classes select p_quiz_id, cid from (select distinct unnest(p_classes) cid) s;
  return v_quiz;
end $$;
revoke all on function public.save_quiz_settings(bigint,text,text,boolean,boolean,integer,bigint[]) from public, anon;
grant execute on function public.save_quiz_settings(bigint,text,text,boolean,boolean,integer,bigint[]) to authenticated;

create or replace function public.set_attempt_deadline() returns trigger language plpgsql security definer set search_path = public as $$
declare minutes integer;
begin
  select time_limit_minutes into minutes from public.quizzes where id = new.quiz_id;
  new.started_at := clock_timestamp();
  new.expires_at := case when minutes is null then null else new.started_at + make_interval(mins => minutes) end;
  return new;
end $$;
drop trigger if exists attempt_deadline on public.attempts;
create trigger attempt_deadline before insert on public.attempts for each row execute function public.set_attempt_deadline();

-- Remove the old unregistered-name entry point so it cannot bypass rosters.
drop function if exists public.start_public_attempt(uuid,text,text);
create or replace function public.start_public_attempt(p_share_token uuid, p_class_id bigint, p_first_name text, p_last_name text)
returns json language plpgsql security definer set search_path = public as $$
declare v_quiz public.quizzes; v_student public.class_students; v_class text; v_id bigint; v_questions bigint[];
begin
  if auth.uid() is null then raise exception 'Please sign in before starting the exam'; end if;
  if public.roster_name(p_first_name) = '' or public.roster_name(p_last_name) = '' then raise exception 'Enter your first and last name'; end if;
  select * into v_quiz from public.quizzes where share_token = p_share_token and is_published;
  if not found then raise exception 'This exam is not available'; end if;
  select c.name into v_class from public.classes c join public.quiz_classes qc on qc.class_id = c.id
    where qc.quiz_id = v_quiz.id and c.id = p_class_id and c.user_id = v_quiz.user_id;
  if not found then raise exception 'Your class is not assigned to this quiz. Contact your teacher.'; end if;
  select * into v_student from public.class_students where class_id = p_class_id
    and public.roster_name(first_name) = public.roster_name(p_first_name) and public.roster_name(last_name) = public.roster_name(p_last_name) for share;
  if not found then raise exception 'Your name is not registered in this class. Check your spelling or contact your teacher.'; end if;
  perform pg_advisory_xact_lock(hashtextextended(v_quiz.id::text || ':' || p_class_id::text || ':' || public.roster_name(p_first_name) || ':' || public.roster_name(p_last_name), 0));
  if exists(select 1 from public.attempts a where a.quiz_id = v_quiz.id and (
    a.roster_student_id = v_student.id or
    (a.class_id = p_class_id and public.roster_name(a.first_name) = public.roster_name(p_first_name) and public.roster_name(a.last_name) = public.roster_name(p_last_name)) or
    (a.first_name is null and public.roster_name(a.student_name) = public.roster_name(v_student.first_name || ' ' || v_student.last_name))
  )) then raise exception 'You have already started an attempt for this quiz. Contact your teacher if you need help.'; end if;
  select array_agg(id order by random()) into v_questions from public.questions where quiz_id = v_quiz.id;
  if coalesce(cardinality(v_questions), 0) = 0 then raise exception 'This exam has no questions yet'; end if;
  insert into public.attempts(quiz_id,user_id,student_name,roster_student_id,class_id,class_name,first_name,last_name)
    values(v_quiz.id,auth.uid(),v_student.first_name || ' ' || v_student.last_name,v_student.id,p_class_id,v_class,v_student.first_name,v_student.last_name) returning id into v_id;
  insert into public.attempt_questions(attempt_id,question_id,"position") select v_id,qid,ord-1 from unnest(v_questions) with ordinality t(qid,ord);
  return public._attempt_payload(v_id);
end $$;
revoke all on function public.start_public_attempt(uuid,bigint,text,text) from public, anon;
grant execute on function public.start_public_attempt(uuid,bigint,text,text) to authenticated;

create or replace function public._attempt_payload(p_attempt_id bigint)
returns json
language plpgsql
security definer set search_path = public
as $$
declare
  result json;
begin
  select json_build_object(
    'id', a.id,
    'quiz', json_build_object('id', qz.id, 'title', qz.title, 'description', qz.description),
    'started_at', a.started_at,
    'completed_at', a.completed_at,
    'score', a.score,
    'total_questions', a.total_questions,
    'student_name', a.student_name,
    'class_name', a.class_name,
    'first_name', a.first_name, 'last_name', a.last_name,
    'expires_at', a.expires_at, 'server_now', clock_timestamp(),
    'termination_reason', a.termination_reason,
    'questions', coalesce((
      select json_agg(json_build_object(
        'id', q.id,
        'type', q.type,
        'prompt', q.prompt,
        'options', q.options,
        'explanation', case when a.completed_at is not null then q.explanation else null end,
        'selected_index', ans.selected_index,
        'answer_text', ans.answer_text,
        'is_correct', case when a.completed_at is not null then ans.is_correct else null end
      ) order by aq."position")
      from public.attempt_questions aq
      join public.questions q on q.id = aq.question_id
      left join public.attempt_answers ans on ans.attempt_id = a.id and ans.question_id = q.id
      where aq.attempt_id = a.id
    ), '[]'::json)
  )
  into result
  from public.attempts a
  join public.quizzes qz on qz.id = a.quiz_id
  where a.id = p_attempt_id;

  return result;
end;
$$;

create or replace function public._finalize_attempt(p_attempt_id bigint, p_reason text default null)
returns json
language plpgsql
security definer set search_path = public
as $$
declare
  v_attempt record;
  v_total int;
  v_score int;
begin
  select * into v_attempt from public.attempts where id = p_attempt_id for update;
  if not found then
    raise exception 'Not found';
  end if;

  if v_attempt.completed_at is not null then
    return public._attempt_payload(p_attempt_id);
  end if;

  if v_attempt.expires_at is not null and clock_timestamp() >= v_attempt.expires_at then
    p_reason := 'time_expired';
  end if;

  insert into public.attempt_answers (attempt_id, question_id, selected_index, answer_text, is_correct, answered_at)
  select p_attempt_id, aq.question_id, null, null, false, null
  from public.attempt_questions aq
  where aq.attempt_id = p_attempt_id
    and not exists (
      select 1 from public.attempt_answers ans
      where ans.attempt_id = p_attempt_id and ans.question_id = aq.question_id
    );

  select count(*) into v_total from public.attempt_questions where attempt_id = p_attempt_id;
  select count(*) into v_score from public.attempt_answers where attempt_id = p_attempt_id and is_correct = true;

  update public.attempts
  set completed_at = case when p_reason = 'time_expired' then v_attempt.expires_at else clock_timestamp() end, score = v_score, total_questions = v_total,
      termination_reason = coalesce(p_reason, termination_reason)
  where id = p_attempt_id;

  return public._attempt_payload(p_attempt_id);
end;
$$;

create or replace function public.submit_answer(
  p_attempt_id bigint,
  p_question_id bigint,
  p_selected_index int default null,
  p_answer_text text default null
)
returns json
language plpgsql
security definer set search_path = public
as $$
declare
  v_attempt record;
  v_question record;
  v_is_correct boolean;
begin
  select * into v_attempt from public.attempts where id = p_attempt_id for update;
  if auth.uid() is null or not found or v_attempt.user_id <> auth.uid() then
    raise exception 'Not found';
  end if;
  if v_attempt.completed_at is null and v_attempt.expires_at is not null and clock_timestamp() >= v_attempt.expires_at then
    perform public._finalize_attempt(p_attempt_id, 'time_expired');
    return json_build_object('ok', false, 'expired', true);
  end if;
  if v_attempt.completed_at is not null then
    raise exception 'Attempt already completed';
  end if;
  if not exists (
    select 1 from public.attempt_questions
    where attempt_id = p_attempt_id and question_id = p_question_id
  ) then
    raise exception 'Question not in attempt';
  end if;

  select * into v_question from public.questions where id = p_question_id;
  if v_question.type in ('multiple_choice', 'true_false') then
    if p_selected_index is null or p_selected_index < 0
      or p_selected_index >= coalesce(jsonb_array_length(v_question.options), 0) then
      raise exception 'Choose a valid answer';
    end if;
    v_is_correct := p_selected_index = v_question.correct_index;
  elsif v_question.type = 'enumeration' then
    if cardinality(public.normalize_enumeration(p_answer_text)) = 0 then
      raise exception 'Enter at least one answer, one per line';
    end if;
    v_is_correct := public.normalize_enumeration(v_question.answer_text)
      = public.normalize_enumeration(p_answer_text);
  else
    if p_answer_text is null or trim(p_answer_text) = '' then
      raise exception 'Answer is required';
    end if;
    v_is_correct := lower(trim(v_question.answer_text)) = lower(trim(p_answer_text));
  end if;

  insert into public.attempt_answers (attempt_id, question_id, selected_index, answer_text, is_correct, answered_at)
  values (
    p_attempt_id, p_question_id,
    case when v_question.type in ('multiple_choice', 'true_false') then p_selected_index else null end,
    case when v_question.type in ('enumeration', 'identification') then trim(p_answer_text) else null end,
    v_is_correct, now()
  )
  on conflict (attempt_id, question_id) do update set
    selected_index = excluded.selected_index,
    answer_text = excluded.answer_text,
    is_correct = excluded.is_correct,
    answered_at = excluded.answered_at;

  return json_build_object('ok', true);
end;
$$;

create or replace function public.get_attempt(p_attempt_id bigint)
returns json
language plpgsql
security definer set search_path = public
as $$
declare
  v_owner uuid;
  v_quiz_owner uuid;
begin
  select a.user_id, q.user_id into v_owner, v_quiz_owner
  from public.attempts a join public.quizzes q on q.id = a.quiz_id
  where a.id = p_attempt_id;

  if v_owner is null then
    raise exception 'Not found';
  end if;

  if auth.uid() is null or (auth.uid() <> v_owner and auth.uid() <> v_quiz_owner) then
    raise exception 'Not found';
  end if;

  if exists(select 1 from public.attempts where id = p_attempt_id and completed_at is null and expires_at <= clock_timestamp()) then
    return public._finalize_attempt(p_attempt_id, 'time_expired');
  end if;
  return public._attempt_payload(p_attempt_id);
end;
$$;

create or replace function public.expire_quiz_attempts(p_quiz_id bigint)
returns void language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  if not public.is_workspace_user() then raise exception 'Workspace account required'; end if;
  for v_id in select a.id from public.attempts a join public.quizzes q on q.id = a.quiz_id
    where a.quiz_id = p_quiz_id and (q.user_id = auth.uid() or a.user_id = auth.uid())
      and a.completed_at is null and a.expires_at <= clock_timestamp() order by a.id
  loop perform public._finalize_attempt(v_id, 'time_expired'); end loop;
end $$;
revoke all on function public.expire_quiz_attempts(bigint) from public, anon;
grant execute on function public.expire_quiz_attempts(bigint) to authenticated;
commit;
